// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CenterRelated: typeof import('./../components/private-components/sy/center-related/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpOpen: typeof import('~icons/ep/open')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    LeftRelated: typeof import('./../components/private-components/sy/left-related/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RightRelated: typeof import('./../components/private-components/sy/right-related/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCenter: typeof import('./../components/private-components/sy/center-related/test-center.vue')['default']
    TestLeft: typeof import('./../components/private-components/sy/left-related/test-left.vue')['default']
    TestRight: typeof import('./../components/private-components/sy/right-related/test-right.vue')['default']
  }
}

export {}
